{{- range $key, $value := .Values.service.ports }}
---
apiVersion: v1
kind: Service
metadata:
  name: seven-days-service-{{ $key }}
  labels:
    app: seven-days-to-die
spec:
  selector:
    app: seven-days-to-die
  type: {{ $.Values.service.type }}
  ports:
    - name: {{ $key }}
      port: {{ $value.port }}
      targetPort: {{ $value.port }}
      nodePort: {{ $value.nodePort }}
      protocol: {{ $value.protocol }}
{{- end }}
